---
title: "class08"
author: "Terry Lin"
date: "10/25/2019"
output:
  github_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## k-means clustering

```{r}
tmp <- c(rnorm(30,-3),rnorm(30,3))
x <- cbind(x=tmp,y=rev(tmp))

plot(x)
k <- kmeans(x,centers=2,nstart=20)

plot(x, col=k$cluster)
points(k$centers, col="blue", pch=15)
```


## hierarchical clustering

```{r}
dist_matrix <- dist(x)
hc <- hclust(d=dist_matrix)
plot(hc)
abline(h=6, col="red")
cutree(hc,k=2)
```

example
```{r}

x <- rbind(
 matrix(rnorm(100, mean=0, sd = 0.3), ncol = 2), # c1
 matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2), # c2
 matrix(c(rnorm(50, mean = 1, sd = 0.3), # c3
 rnorm(50, mean = 0, sd = 0.3)), ncol = 2))
colnames(x) <- c("x","y")
plot(x)
col<- as.factor(rep(c("c1","c2","c3"), each=50))
plot(x, col=col)


hclust<- hclust(dist(x))
plot(hclust)
groups<-cutree(hclust,k=3)
table(col,groups)
plot(x,col=groups)
  
```



## Principal ComponentAnalysis (PCA)
Looking at gene expression comparing two or more types
positive correlation: possibly same function or same cells
negative correlation: different cells, different function

PCs (dimensions) are ranked by importance (1,2,3..)
ranked by amount of variance in original data

```{r}
data_gene<- read.csv("C:/Users/Terry/Desktop/R/class08/expression.csv", row.names = 1)
data_food<- read.csv("C:/Users/Terry/Desktop/R/class08/UK_foods.csv", row.names = 1)

#tells us how many rows/columns
dim(data_food)
head(data_gene)
#t function transposes matrix, sample becomes rows and genes becomes columns
head(t(data_gene))
```
```{r}
pca1 <- prcomp(t(data_gene),scale=TRUE)

attributes(pca1)
summary(pca1)
colvec <- as.factor(substr(colnames(data_gene),1,2))
pca.var<- pca1$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100,1)
pca.var.per
plot(pca1$x[,1],pca1$x[,2], col=colvec,pch=16,
     xlab=paste0("PC1 (",pca.var.per[1], "%)"),
     ylab=paste0("PC2 (",pca.var.per[2], "%)"))



barplot(pca.var.per, main="Scree Plot", xlab= "Principal Component", ylab= "Percent Variation")
```


```{r}
head(data_food)
barplot(as.matrix(data_food),beside=F, col=rainbow(nrow(data_food)))
pairs(data_food, col=rainbow(10),pch=16)

pca2<- prcomp(t(data_food))
summary(pca2)
plot(pca2$x[,1],pca2$x[,2], xlab="PC1", ylab="PC2", xlim= c(-300,500))
color<- c("orange","red","blue","green")
text(pca2$x[,1], pca2$x[,2],colnames(data_food),col=color)

```

```{r}
v <- round(pca2$sdev^2/sum(pca2$sdev^2) *100)
v
z<- summary(pca2)
z$importance
barplot(v, xlab="Principal Component", ylab="Percent Variation")


par(mar=c(10,3,0.35,0))
barplot(pca2$rotation[,1],las=2)
barplot(pca2$rotation[,2],las=2)

biplot(pca2)
```











